SAMPLE_PLAYER_STATS = [
    {
        "external_id": "sample-player-mex-forward",
        "competition": "FIFA World Cup 2026",
        "stage": "Group Stage",
        "group_name": "Group A",
        "team": "Mexico",
        "team_code": "MEX",
        "player_name": "Mexico Forward",
        "position": "Forward",
        "shirt_number": 9,
        "appearances": 1,
        "goals": 1,
        "assists": 2,
        "yellow_cards": 0,
        "red_cards": 0,
        "minutes_played": 90,
    },
    {
        "external_id": "sample-player-mex-midfielder",
        "competition": "FIFA World Cup 2026",
        "stage": "Group Stage",
        "group_name": "Group A",
        "team": "Mexico",
        "team_code": "MEX",
        "player_name": "Mexico Midfielder",
        "position": "Midfielder",
        "shirt_number": 8,
        "appearances": 1,
        "goals": 1,
        "assists": 0,
        "yellow_cards": 1,
        "red_cards": 0,
        "minutes_played": 86,
    },
    {
        "external_id": "sample-player-usa-forward",
        "competition": "FIFA World Cup 2026",
        "stage": "Group Stage",
        "group_name": "Group D",
        "team": "United States",
        "team_code": "USA",
        "player_name": "United States Forward",
        "position": "Forward",
        "shirt_number": 11,
        "appearances": 1,
        "goals": 3,
        "assists": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "minutes_played": 90,
    },
    {
        "external_id": "sample-player-usa-creator",
        "competition": "FIFA World Cup 2026",
        "stage": "Group Stage",
        "group_name": "Group D",
        "team": "United States",
        "team_code": "USA",
        "player_name": "United States Creator",
        "position": "Midfielder",
        "shirt_number": 10,
        "appearances": 1,
        "goals": 0,
        "assists": 3,
        "yellow_cards": 0,
        "red_cards": 0,
        "minutes_played": 88,
    },
    {
        "external_id": "sample-player-fra-striker",
        "competition": "FIFA World Cup 2026",
        "stage": "Group Stage",
        "group_name": "Group I",
        "team": "France",
        "team_code": "FRA",
        "player_name": "France Striker",
        "position": "Forward",
        "shirt_number": 9,
        "appearances": 1,
        "goals": 2,
        "assists": 0,
        "yellow_cards": 0,
        "red_cards": 0,
        "minutes_played": 84,
    },
    {
        "external_id": "sample-player-fra-defender",
        "competition": "FIFA World Cup 2026",
        "stage": "Group Stage",
        "group_name": "Group I",
        "team": "France",
        "team_code": "FRA",
        "player_name": "France Defender",
        "position": "Defender",
        "shirt_number": 4,
        "appearances": 1,
        "goals": 0,
        "assists": 1,
        "yellow_cards": 1,
        "red_cards": 0,
        "minutes_played": 90,
    },
    {
        "external_id": "sample-player-arg-captain",
        "competition": "FIFA World Cup 2026",
        "stage": "Group Stage",
        "group_name": "Group J",
        "team": "Argentina",
        "team_code": "ARG",
        "player_name": "Argentina Captain",
        "position": "Forward",
        "shirt_number": 10,
        "appearances": 1,
        "goals": 2,
        "assists": 1,
        "yellow_cards": 0,
        "red_cards": 0,
        "minutes_played": 90,
    },
    {
        "external_id": "sample-player-arg-defender",
        "competition": "FIFA World Cup 2026",
        "stage": "Group Stage",
        "group_name": "Group J",
        "team": "Argentina",
        "team_code": "ARG",
        "player_name": "Argentina Defender",
        "position": "Defender",
        "shirt_number": 6,
        "appearances": 1,
        "goals": 0,
        "assists": 0,
        "yellow_cards": 1,
        "red_cards": 1,
        "minutes_played": 74,
    },
]
