from datetime import datetime, timezone
import time

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import or_
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.config import settings
from app.database import get_db
from app.models.fixture import Fixture
from app.models.match_detail import MatchDetail
from app.providers.api_football import ApiFootballProviderError
from app.providers.factory import get_configured_football_provider
from app.providers.zafronix import ZafronixProviderError
from app.services.fixture_sync_service import sync_fixtures
from app.services.metrics_service import (
    record_fixture_sync_metrics,
    record_notification_result,
)
from app.services.sample_data import SAMPLE_FIXTURES
from app.services.sync_observability_service import (
    get_fixture_sync_status,
    list_fixture_sync_runs,
    record_fixture_sync_status,
    sanitize_sync_error,
)
from app.services.telegram_notifier import (
    TelegramNotificationError,
    send_completed_fixture_notifications,
)

router = APIRouter(
    prefix="/fixtures",
    tags=["fixtures"],
)


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


def serialize_fixture(fixture: Fixture) -> dict:
    return {
        "id": fixture.id,
        "external_id": fixture.external_id,
        "competition": fixture.competition,
        "stage": fixture.stage,
        "group_name": fixture.group_name,
        "home_team": fixture.home_team,
        "away_team": fixture.away_team,
        "home_team_code": fixture.home_team_code,
        "away_team_code": fixture.away_team_code,
        "kickoff_time": fixture.kickoff_time,
        "venue": fixture.venue,
        "status": fixture.status,
        "home_score": fixture.home_score,
        "away_score": fixture.away_score,
        "created_at": fixture.created_at,
        "updated_at": fixture.updated_at,
    }


def serialize_match_detail(match_detail: MatchDetail) -> dict:
    return {
        "id": match_detail.id,
        "fixture_id": match_detail.fixture_id,
        "provider": match_detail.provider,
        "provider_match_id": match_detail.provider_match_id,
        "goals": match_detail.goals or [],
        "cards": match_detail.cards or [],
        "substitutions": match_detail.substitutions or [],
        "formations": match_detail.formations or {},
        "lineups": match_detail.lineups or {},
        "statistics": match_detail.statistics or {},
        "referee": match_detail.referee or {},
        "weather": match_detail.weather or {},
        "created_at": match_detail.created_at,
        "updated_at": match_detail.updated_at,
    }


def notify_newly_completed_fixtures(
    db: Session,
    newly_completed_external_ids: list[str],
) -> dict:
    """
    Dispatch completed-match Telegram alerts only when explicitly enabled.

    Manual Telegram test notifications remain available at
    /notifications/telegram/test. This policy only controls alerts generated by
    fixture syncs.
    """
    if not settings.telegram_completed_match_alerts_enabled:
        record_notification_result(
            channel="telegram",
            status="skipped",
        )

        return {
            "status": "skipped",
            "reason": "Completed-match Telegram alerts are disabled by configuration.",
            "sent": 0,
        }

    if not newly_completed_external_ids:
        record_notification_result(
            channel="telegram",
            status="skipped",
        )

        return {
            "status": "skipped",
            "reason": "No newly completed fixtures",
            "sent": 0,
        }

    fixtures = (
        db.query(Fixture)
        .filter(Fixture.external_id.in_(newly_completed_external_ids))
        .all()
    )

    serialized_fixtures = [serialize_fixture(fixture) for fixture in fixtures]

    try:
        result = send_completed_fixture_notifications(serialized_fixtures)

        record_notification_result(
            channel="telegram",
            status="sent",
        )

        return {
            "status": "sent",
            "sent": result["sent"],
        }

    except ValueError as error:
        record_notification_result(
            channel="telegram",
            status="skipped",
        )

        return {
            "status": "skipped",
            "reason": str(error),
            "sent": 0,
        }

    except TelegramNotificationError as error:
        record_notification_result(
            channel="telegram",
            status="failed",
        )

        return {
            "status": "failed",
            "reason": str(error),
            "sent": 0,
        }


def _record_sync_success(
    db: Session,
    source: str,
    provider_name: str,
    result: dict,
    duration_seconds: float,
    started_at: str,
) -> None:
    record_fixture_sync_metrics(
        source=source,
        provider=provider_name,
        status="success",
        result=result,
        duration_seconds=duration_seconds,
    )
    record_fixture_sync_status(
        db=db,
        source=source,
        provider=provider_name,
        status="success",
        result=result,
        duration_seconds=duration_seconds,
        trigger_type="manual",
        started_at=started_at,
    )


def _record_sync_failure(
    db: Session,
    source: str,
    provider_name: str,
    duration_seconds: float,
    error_message: str,
    started_at: str,
) -> None:
    record_fixture_sync_metrics(
        source=source,
        provider=provider_name,
        status="error",
        duration_seconds=duration_seconds,
    )
    record_fixture_sync_status(
        db=db,
        source=source,
        provider=provider_name,
        status="error",
        duration_seconds=duration_seconds,
        error=error_message,
        trigger_type="manual",
        started_at=started_at,
    )


@router.get("")
def list_fixtures(
    group_name: str | None = Query(
        default=None,
        description="Filter fixtures by group name, for example: Group A",
    ),
    status: str | None = Query(
        default=None,
        description="Filter fixtures by status, for example: scheduled, complete, or live",
    ),
    team: str | None = Query(
        default=None,
        description="Search fixtures by team name or team code",
    ),
    db: Session = Depends(get_db),
):
    try:
        query = db.query(Fixture)

        if group_name:
            query = query.filter(Fixture.group_name == group_name)

        if status:
            query = query.filter(Fixture.status == status)

        if team:
            team_search = f"%{team}%"
            query = query.filter(
                or_(
                    Fixture.home_team.ilike(team_search),
                    Fixture.away_team.ilike(team_search),
                    Fixture.home_team_code.ilike(team_search),
                    Fixture.away_team_code.ilike(team_search),
                )
            )

        fixtures = query.order_by(Fixture.kickoff_time.asc()).all()

        return {
            "count": len(fixtures),
            "filters": {
                "group_name": group_name,
                "status": status,
                "team": team,
            },
            "fixtures": [serialize_fixture(fixture) for fixture in fixtures],
        }

    except SQLAlchemyError as error:
        raise HTTPException(
            status_code=503,
            detail=f"Database error while listing fixtures: {error}",
        ) from error


@router.get("/sync/status")
def get_fixture_sync_runtime_status(db: Session = Depends(get_db)):
    return get_fixture_sync_status(db)


@router.get("/sync/history")
def get_fixture_sync_history(
    limit: int = Query(
        default=10,
        ge=1,
        le=50,
        description="Maximum number of recent persisted fixture sync runs",
    ),
    db: Session = Depends(get_db),
):
    runs = list_fixture_sync_runs(db, limit=limit)

    return {
        "count": len(runs),
        "runs": runs,
    }




COMPLETED_FIXTURE_STATUSES = {
    "complete",
    "completed",
    "finished",
    "final",
    "ft",
    "aet",
    "pen",
    "full-time",
    "full time",
    "match finished",
}


def _is_completed_fixture_status(status: str | None) -> bool:
    normalized_status = (
        str(status or "")
        .strip()
        .lower()
        .replace("_", " ")
    )
    return normalized_status in COMPLETED_FIXTURE_STATUSES


def _build_empty_event_quality_coverage() -> dict:
    return {
        "fixtures_with_recorded_events": 0,
        "fixtures_with_no_stored_events": 0,
        "fixtures_without_stored_detail": 0,
        "total_stored_events": 0,
    }


def _build_match_data_quality_response(
    fixtures: list[Fixture],
    detail_by_fixture_id: dict[int, MatchDetail],
    group_name: str | None,
    team: str | None,
    missing_detail_limit: int,
) -> dict:
    """
    Aggregate only local stored match-detail coverage.

    This is a read-only dashboard contract. It never triggers a provider request,
    sync, backfill, notification, or any database write.
    """
    completed_fixtures = [
        fixture
        for fixture in fixtures
        if _is_completed_fixture_status(fixture.status)
    ]
    completed_fixture_count = len(completed_fixtures)

    event_coverage = {
        "goals": _build_empty_event_quality_coverage(),
        "cards": _build_empty_event_quality_coverage(),
        "substitutions": _build_empty_event_quality_coverage(),
    }

    fixtures_with_stored_detail = 0
    missing_detail_fixtures: list[Fixture] = []
    stored_detail_updated_at: list[str] = []

    for fixture in completed_fixtures:
        match_detail = detail_by_fixture_id.get(fixture.id)

        if match_detail is None:
            missing_detail_fixtures.append(fixture)

            for coverage in event_coverage.values():
                coverage["fixtures_without_stored_detail"] += 1

            continue

        fixtures_with_stored_detail += 1

        if match_detail.updated_at:
            stored_detail_updated_at.append(match_detail.updated_at)

        for event_name in event_coverage:
            raw_events = getattr(match_detail, event_name, None)
            event_count = len(raw_events) if isinstance(raw_events, list) else 0
            coverage = event_coverage[event_name]

            if event_count > 0:
                coverage["fixtures_with_recorded_events"] += 1
                coverage["total_stored_events"] += event_count
            else:
                coverage["fixtures_with_no_stored_events"] += 1

    fixtures_without_stored_detail = len(missing_detail_fixtures)

    if completed_fixture_count == 0:
        state = "unavailable"
        coverage_percent = None
        message = (
            "No completed fixtures are available in this scope. "
            "Stored match-detail coverage cannot be calculated."
        )
    else:
        coverage_percent = round(
            (fixtures_with_stored_detail / completed_fixture_count) * 100,
            1,
        )

        if fixtures_with_stored_detail == completed_fixture_count:
            state = "complete"
        elif fixtures_with_stored_detail > 0:
            state = "partial"
        else:
            state = "unavailable"

        message = (
            f"{fixtures_with_stored_detail} of {completed_fixture_count} completed "
            "fixtures have stored provider match detail in this scope."
        )

    return {
        "filters": {
            "group_name": group_name,
            "team": team,
        },
        "summary": {
            "state": state,
            "scope_fixture_count": len(fixtures),
            "completed_fixture_count": completed_fixture_count,
            "fixtures_with_stored_detail": fixtures_with_stored_detail,
            "fixtures_without_stored_detail": fixtures_without_stored_detail,
            "coverage_percent": coverage_percent,
            "latest_stored_detail_updated_at": (
                max(stored_detail_updated_at)
                if stored_detail_updated_at
                else None
            ),
        },
        "event_coverage": event_coverage,
        "missing_detail_fixture_count": fixtures_without_stored_detail,
        "missing_detail_limit": missing_detail_limit,
        "missing_detail_fixtures": [
            serialize_fixture(fixture)
            for fixture in missing_detail_fixtures[:missing_detail_limit]
        ],
        "message": message,
    }


@router.get("/data-quality")
def get_match_data_quality(
    group_name: str | None = Query(
        default=None,
        description="Limit stored match-detail coverage to one group.",
    ),
    team: str | None = Query(
        default=None,
        description="Limit stored match-detail coverage to a team name or code.",
    ),
    missing_detail_limit: int = Query(
        default=12,
        ge=1,
        le=50,
        description="Maximum missing-detail fixtures returned for dashboard follow-up.",
    ),
    db: Session = Depends(get_db),
):
    """
    Return local stored match-detail coverage without contacting a provider.

    The scope includes all fixtures matching the optional group/team filters. The
    coverage counters themselves apply only to completed fixtures in that scope.
    """
    try:
        query = db.query(Fixture)

        if group_name:
            query = query.filter(Fixture.group_name == group_name)

        if team:
            team_search = f"%{team}%"
            query = query.filter(
                or_(
                    Fixture.home_team.ilike(team_search),
                    Fixture.away_team.ilike(team_search),
                    Fixture.home_team_code.ilike(team_search),
                    Fixture.away_team_code.ilike(team_search),
                )
            )

        fixtures = query.order_by(Fixture.kickoff_time.asc()).all()
        fixture_ids = [fixture.id for fixture in fixtures]

        detail_by_fixture_id: dict[int, MatchDetail] = {}

        if fixture_ids:
            details = (
                db.query(MatchDetail)
                .filter(MatchDetail.fixture_id.in_(fixture_ids))
                .all()
            )
            detail_by_fixture_id = {
                detail.fixture_id: detail
                for detail in details
            }

        return _build_match_data_quality_response(
            fixtures=fixtures,
            detail_by_fixture_id=detail_by_fixture_id,
            group_name=group_name,
            team=team,
            missing_detail_limit=missing_detail_limit,
        )

    except SQLAlchemyError as error:
        raise HTTPException(
            status_code=503,
            detail=f"Database error while reading match data quality: {error}",
        ) from error


@router.get("/{fixture_id}/detail")
def get_fixture_detail(fixture_id: int, db: Session = Depends(get_db)):
    try:
        fixture = db.query(Fixture).filter(Fixture.id == fixture_id).first()

        if fixture is None:
            raise HTTPException(
                status_code=404,
                detail="Fixture not found",
            )

        match_detail = (
            db.query(MatchDetail)
            .filter(MatchDetail.fixture_id == fixture.id)
            .first()
        )

        return {
            "fixture": serialize_fixture(fixture),
            "detail_available": match_detail is not None,
            "detail": (
                serialize_match_detail(match_detail)
                if match_detail is not None
                else None
            ),
        }

    except SQLAlchemyError as error:
        raise HTTPException(
            status_code=503,
            detail=f"Database error while getting fixture detail: {error}",
        ) from error


@router.get("/{fixture_id}")
def get_fixture(fixture_id: int, db: Session = Depends(get_db)):
    try:
        fixture = db.query(Fixture).filter(Fixture.id == fixture_id).first()

        if fixture is None:
            raise HTTPException(
                status_code=404,
                detail="Fixture not found",
            )

        return serialize_fixture(fixture)

    except SQLAlchemyError as error:
        raise HTTPException(
            status_code=503,
            detail=f"Database error while getting fixture: {error}",
        ) from error


@router.post("/sync/sample")
def sync_sample_fixtures(db: Session = Depends(get_db)):
    source = "sample"
    provider_name = "sample_data"
    started_at = _utc_now_iso()
    start_time = time.perf_counter()

    try:
        result = sync_fixtures(db, SAMPLE_FIXTURES)
        duration_seconds = time.perf_counter() - start_time

        _record_sync_success(
            db=db,
            source=source,
            provider_name=provider_name,
            result=result,
            duration_seconds=duration_seconds,
            started_at=started_at,
        )

        notification_result = notify_newly_completed_fixtures(
            db,
            result["newly_completed"],
        )

        return {
            "message": "Sample fixtures synced successfully",
            "provider": provider_name,
            "created": result["created"],
            "updated": result["updated"],
            "total_sample_fixtures": result["total_fixtures"],
            "newly_completed_count": result["newly_completed_count"],
            "newly_completed": result["newly_completed"],
            "duration_seconds": duration_seconds,
            "notifications": notification_result,
        }

    except SQLAlchemyError as error:
        db.rollback()
        duration_seconds = time.perf_counter() - start_time
        error_message = sanitize_sync_error(
            f"Database error while syncing sample fixtures: {error}"
        ) or "Database error while syncing sample fixtures."

        try:
            _record_sync_failure(
                db=db,
                source=source,
                provider_name=provider_name,
                duration_seconds=duration_seconds,
                error_message=error_message,
                started_at=started_at,
            )
        except SQLAlchemyError:
            db.rollback()

        raise HTTPException(
            status_code=503,
            detail=error_message,
        ) from error


@router.post("/sync/provider")
def sync_provider_fixtures(db: Session = Depends(get_db)):
    source = "provider"
    provider_name = "unknown"
    started_at = _utc_now_iso()
    start_time = time.perf_counter()

    try:
        provider_name, provider = get_configured_football_provider()
        fixtures = provider.get_world_cup_fixtures()
        result = sync_fixtures(db, fixtures)
        duration_seconds = time.perf_counter() - start_time

        _record_sync_success(
            db=db,
            source=source,
            provider_name=provider_name,
            result=result,
            duration_seconds=duration_seconds,
            started_at=started_at,
        )

        notification_result = notify_newly_completed_fixtures(
            db,
            result["newly_completed"],
        )

        return {
            "message": "Provider fixtures synced successfully",
            "provider": provider_name,
            "created": result["created"],
            "updated": result["updated"],
            "total_provider_fixtures": result["total_fixtures"],
            "newly_completed_count": result["newly_completed_count"],
            "newly_completed": result["newly_completed"],
            "duration_seconds": duration_seconds,
            "notifications": notification_result,
        }

    except ValueError as error:
        duration_seconds = time.perf_counter() - start_time
        error_message = sanitize_sync_error(str(error)) or "Provider sync failed."

        _record_sync_failure(
            db=db,
            source=source,
            provider_name=provider_name,
            duration_seconds=duration_seconds,
            error_message=error_message,
            started_at=started_at,
        )

        raise HTTPException(
            status_code=400,
            detail=error_message,
        ) from error

    except (ApiFootballProviderError, ZafronixProviderError) as error:
        duration_seconds = time.perf_counter() - start_time
        error_message = sanitize_sync_error(str(error)) or "Provider sync failed."

        _record_sync_failure(
            db=db,
            source=source,
            provider_name=provider_name,
            duration_seconds=duration_seconds,
            error_message=error_message,
            started_at=started_at,
        )

        raise HTTPException(
            status_code=502,
            detail=error_message,
        ) from error

    except SQLAlchemyError as error:
        db.rollback()
        duration_seconds = time.perf_counter() - start_time
        error_message = sanitize_sync_error(
            f"Database error while syncing provider fixtures: {error}"
        ) or "Database error while syncing provider fixtures."

        try:
            _record_sync_failure(
                db=db,
                source=source,
                provider_name=provider_name,
                duration_seconds=duration_seconds,
                error_message=error_message,
                started_at=started_at,
            )
        except SQLAlchemyError:
            db.rollback()

        raise HTTPException(
            status_code=503,
            detail=error_message,
        ) from error
